# Generated by Django 5.0.4 on 2024-06-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradesheet', '0002_alter_grade_options_grade_date_grade_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date', 'student'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
